<?php
require_once('functions.php');
require_once('new_config.php');
require_once('classes/database.php');
require_once('classes/session.php');
require_once('classes/dbClass.php');
//require_once('classes/user.php');
//require_once('classes/photo.php');
//include('user.php');
